### ISSUE TITLE
配合 zap 使用，切分时报错

### ISSUE THREAD

**Issue by liudaoping** [arthurkiller/rollingwriter#11]
在配合 zap 使用时，当要切分时，出现以下错误
write error: rename log/logs.log log/logs.log.201905111642: The process cannot access the file because it is being **used by another process**.

从提示上看，当要切分时，log 文件被占用了，不能重命名

我构建 zap logger 代码如下：
`
	// 基本上与 demo 例子相同的配置进行构建的 RollingWriter 实例
	rw, _ := newRollingWriter(&config)

	// 基于 RollingWriter 构建 *zap.Logger
	ws := zapcore.AddSync(rw)
	core := zapcore.NewCore(
		zapcore.NewJSONEncoder(zap.NewProductionEncoderConfig()),
		ws,
		zap.InfoLevel,
	)

	logger = zap.New(core)`

ps. rollingWriter 代码获取的是 master 分支

**Comment by arthurkiller** [comment]
能否提供下更详细的配置呢？ @liudaoping

**Comment by arthurkiller** [comment]
> ws := zapcore.AddSync(rw)

这个其实不需要

**Comment by liudaoping** [comment]
@arthurkiller 
您好，作者大大，
我的配置如下：
```
	config := rollingwriter.Config{
		LogPath:  "./log",
		FileName: "logs",

		TimeTagFormat: "200601021504",
		MaxRemain:     -1,

		RollingPolicy:      rollingwriter.TimeRolling,
		RollingTimePattern: "*/10 * * * * *", // 便于测试，设置每10秒进行切分

		WriterMode: "lock",
	}
```

另外
`ws := zapcore.AddSync(rw)`

这个如果不需要，如何传递构建的 RollingWriter 实例?

**Comment by arthurkiller** [comment]
@liudaoping 感谢回复，我来测试一下这个问题。

**Comment by arthurkiller** [comment]
@liudaoping 我试了下，目前没有复现

不过基于你提供的配置， 日志文件的时间是按照分钟编码，但是日志切分是按照秒，因此这里可能会有重新覆盖掉的情况。

你提到的错误是否还有发生，如果有可以多贴一点日志错误出来

**Comment by liudaoping** [comment]
@arthurkiller 

> 不过基于你提供的配置， 日志文件的时间是按照分钟编码，但是日志切分是按照秒

我分别设置了日志文件按秒编码、日志按照每分钟切分，还是会出现上述错误！


> 你提到的错误是否还有发生，如果有可以多贴一点日志错误出来

没有更多的错误日志，基本上就是上述错误信息，以下是一条完整的错误信息：
`2019-05-15 14:49:00.133358 +0800 CST m=+37.457047501 write error: rename log/logs.log log/logs.log.20190515144823: The process cannot access the file because it is being used by another process.`

另外以下是我的代码：
```
	// rolling 配置
	config := rollingwriter.Config{
		LogPath:  "./log",
		FileName: "logs",

		TimeTagFormat: "20060102150405",
		MaxRemain:     -1,

		RollingPolicy:      rollingwriter.TimeRolling,
		RollingTimePattern: "0 */1 * * * *",

		WriterMode: "lock",
	}

	// 创建 writer
	w, _ := rollingwriter.NewWriterFromConfig(&config)

	// 创建 logger
	ws := zapcore.AddSync(w)
	encoderCfg := zap.NewProductionEncoderConfig()
	encoder := zapcore.NewJSONEncoder(encoderCfg)
	core := zapcore.NewCore(
		encoder,
		ws,
		zap.InfoLevel,
	)

	lg := zap.New(core)

	// 测试日志打印
	count := 1
	for {

		lg.Info("message "+strconv.Itoa(count),
			zap.String("label", "log "+strconv.Itoa(count)),
			zap.String("module", "log testing"))

		count++

		time.Sleep(500 * time.Millisecond)
	}
```
@arthurkiller 请帮忙看看是否哪里出了问题

**Comment by arthurkiller** [comment]
@liudaoping 
![image](https://user-images.githubusercontent.com/11133870/57756149-3e0c4e80-7725-11e9-9026-d22fb06f9577.png)
我这边没有复现，感觉不是 writer 的错误，如果有类似的错误话应该很严重，但是目前很多项目使用了并没有提出 issue。

建议检查下你的 log 文件是不是被别的程序并发访问了。

我测试环境： 
```
mac osx 10.14.4 (18E226)
zap 67bc79d13d155c02fd008f721863ff8cc5f30659

**Comment by arthurkiller** [comment]
btw 关于你提出的错误， 我搜索了下， 有以下的地方提出了这个错误


```

golang/pkg/dep/sources/https---github.com-pingcap-pd/vendor/github.com/coreos/etcd/pkg/fileutil/lock_windows.go
31:     errLocked = errors.New("The process cannot access the file because another process has locked a portion of the file.")

golang/pkg/dep/sources/https---************* vendor/github.com/coreos/etcd/pkg/fileutil/lock_windows.go
31:     errLocked = errors.New("The process cannot access the file because another process has locked a portion of the file.")
```

**Comment by liudaoping** [comment]
@arthurkiller 
您好，作者大大，
当看到你是用 mac os 无法重现的时候，我猜测应该是**平台特定**因素引起的.
我是在 windows 环境下运行代码出现的错误；经过在 Linux 环境测试，**确实不会**出现错误，所以目前可以确定**在 windows 环境**会出现该错误。

经过调试与查看源码，windows 环境下进行重命名的时候，调用的是底层的 MoveFileEx 方法，所以在**原文件未关闭**的情况下，不能重命名成功。

我查看了您写的 **Reopen 方法**的实现，然后给出一点小建议，您看看是否可行？
1. 先把旧文件关闭
2. 再进行重命名操作
3. 创建新文件
4. 在开启的 goroutine 里用重命名后的文件进行压缩操作（目前您的实现是用旧文件进行压缩，再进行关闭）
5. 其它不变

主要思路就是把旧文件的关闭前置

**Comment by arthurkiller** [comment]
当前的逻辑是这样的

```golang
// Reopen do the rotate, open new file and swap FD then trate the old FD
func (w *Writer) Reopen(file string) error {
    if err := os.Rename(w.absPath, file); err != nil {
        return err
    }
 <<<<<<<<<<<<<<<< 此时仍然可以写旧文件

    newfile, err := os.OpenFile(w.absPath, DefaultFileFlag, DefaultFileMode)
    if err != nil {
        return err
    }

    // swap the unsafe pointer
    oldfile := atomic.SwapPointer((*unsafe.Pointer)(unsafe.Pointer(&w.file)), unsafe.Pointer(newfile))
<<<<<<<<<<<<<<<<< 此时通过原子操作，读写切换到新文件，旧文件应该不再有读写请求

    go func() {
        defer (*os.File)(oldfile).Close()
《》《》《》《》《》《
<<<<<<<<<<<<<  需要在读完整个文件，（压缩）之后再关闭
        if w.cf.Compress {
            if err := os.Rename(file, file+".tmp"); err != nil {
                log.Println("error in compress rename tempfile", err)
                return
            }
            if err := w.CompressFile((*os.File)(oldfile), file); err != nil {
                log.Println("error in compress log file", err)
                return
            }
        }

        if w.cf.MaxRemain > 0 {
        retry:
            select {
            case w.rollingfilech <- file:
            default:
                w.DoRemove()
                goto retry // remove the file and retry
            }
        }
    }()
    return nil
}
```

**Comment by arthurkiller** [comment]
这里的原因是这样： 假设日志文件叫 `access.log`

如果按照 `windows` 上的情况，改名操作需要在日志文件关闭的时候进行。如果我需要最新未切割的日志打印到 `access.log` 就必须有一个时刻 2 个文件都关闭的。这个是不符合我的想法的。

不过，你说的这个 `windows` 上的问题，确实我没有遇到过。我看看能不能通过跨平台的实现方式来解决，这个 issue 我先留着吧

**Comment by arthurkiller** [comment]
不过， 这个错误是你在使用 etcd 出的错吧？你是把日志 set 到 etcd 里面了？我搜索了整个代码库，都没有这个错误提示。

**Comment by liudaoping** [comment]
@arthurkiller 

> 就必须有一个时刻 2 个文件都关闭的。这个是不符合我的想法的

在并发或异步的时候，是否可以提供检测 reopen 的状态机制？
在写之前判断若 reopen 状态，没有好的情况下，挂起写操作，reopen 完成，继续进行写操作


> 我搜索了整个代码库，都没有这个错误提示

错误提示其实是在 zap 代码打印出来的，但错误是在 Reopen 方法里的 **Rename 操作引发**的：
Reopen 里引发错误：
![image](https://user-images.githubusercontent.com/19853499/57847325-c31c6400-7808-11e9-906d-453c690a643a.png)

go.uber.org/zap/zapcore/entry.go 文件里的 Write 方法打印错误：
![image](https://user-images.githubusercontent.com/19853499/57847376-e6dfaa00-7808-11e9-9aea-f6844f12e65a.png)

**Comment by arthurkiller** [comment]
设计的时候是希望 `Reopen` 这个动作通过原子的方式直接 set 指针，避免加锁。

我想了下有 2 个方式：
1. 对于 windows 单独实现一个 `Reopen` 函数，通过跨平台方式编译。这种能够解决 win 的问题。
2. Override `Reopen` 函数，不保证所有写都无感知。但是在超大的写入场景下，切分时会有抖动

**Comment by sky126** [comment]
> 设计的时候是希望 `Reopen` 这个动作通过原子的方式直接 set 指针，避免加锁。
> 
> 我想了下有 2 个方式：
> 
> 1. 对于 windows 单独实现一个 `Reopen` 函数，通过跨平台方式编译。这种能够解决 win 的问题。
> 2. Override `Reopen` 函数，不保证所有写都无感知。但是在超大的写入场景下，切分时会有抖动。
> 
> @chaomai 如何

@arthurkiller  windows 下面确实有这个错误好在我只是在window下开发，第一种方式好一些。

**Comment by arthurkiller** [comment]
fixed via #39
