### ISSUE TITLE
请问master代码是否可用？

### ISSUE THREAD

**Issue by spiderpoison** [arthurkiller/rollingWriter#2]
跑了一个小例子：
```
config := rollingwriter.Config{
	LogPath:           "./log",
	TimeTagFormat:     "060102150405",
	FileName:          "test",
	MaxRemain:         5,
	RollingPolicy:     rollingwriter.VolumeRolling,
	RollingVolumeSize: "2K",
	Asynchronous:      true,
}
writer, err := rollingwriter.NewWriterFromConfig(&config)
if err != nil {
	// 应该处理错误
	panic(err)
}
wg := sync.WaitGroup{}
wg.Add(1)
go func() {
	for {
		bf := []byte(fmt.Sprintf("rollingwriter test write gorounter time %v\n", time.Now()))
		writer.Write(bf)
	}
}()
wg.Wait()
```
运行了一段时间，输出如下，也没有按照2k切分：
![default](https://user-images.githubusercontent.com/7857870/45345811-05d2d000-b5da-11e8-882a-b7d3250197c8.png)
里面的内容也是不可读的

**Comment by arthurkiller** [comment]
先试试 dev?  似乎是没有合并到 master 呢, 我稍后试一下啊
@spiderpoison

**Comment by spiderpoison** [comment]
dev分支的表现好像也不太行，运行了下上面的小例子，结果文件里还是乱码
![default](https://user-images.githubusercontent.com/7857870/45346613-37e53180-b5dc-11e8-90db-f1a88c771cc7.png)

**Comment by arthurkiller** [comment]
收到, 我看下

**Comment by arthurkiller** [comment]
嗯, ansyc 似乎有点问题, 我看下, 可以先用同步的 writer

> 	Asynchronous:      false,
>     Lock :  true,

**Comment by spiderpoison** [comment]
如果方便的话，能否加个时区的配置参数，用作TimeRolling的时间的时区

**Comment by arthurkiller** [comment]
这个是说按照不同时区的时间？因为我这个配置的是当地时间，你是想用协调时是么？

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️

Arthur lee

**Comment by spiderpoison** [comment]
目前用的是time.Location，但如果一个服务涉及到多个时区（一般日志和bilog的时区就不同），就不能满足需求了。
因此，需要能根据需求自己设置时区，主要用来分割log文件

**Comment by arthurkiller** [comment]
明白了, 这里有2个点:

1. 切分的时间点, 这个是由 cron 类似的配置决定的, 因此, 只能是配置当地时间的某个策略来执行切分

2. 生成日志文件的时间戳格式, 这个可以通过 option 来调整 filename 的 format

这样满足需求么? @spiderpoison

**Comment by spiderpoison** [comment]
关于上述第一点，rollingwriter的TimeRolling模式是根据时间戳生成文件名，比如当跨天的时候，文件名变化了，就会导致切分，是这样的吗？
如果是这样的，时区配置就可以影响文件切分了

**Comment by spiderpoison** [comment]
请问ansyc模式什么时候可以用吗？

**Comment by arthurkiller** [comment]
你的业务需求是什么样，为什么需要异步？

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️

Arthur lee

**Comment by spiderpoison** [comment]
为了配合zap使用，因为zap日志输出本身是同步的，为了不让IO影响到正常逻辑的性能，打算配合异步落地方案。

**Comment by arthurkiller** [comment]
为了配合zap使用，因为zap日志输出本身是同步的，为了不让IO影响到正常逻辑的性能，打算配合异步落地方案。

=============

这个本身是不对的啊,  不会影响到正常逻辑, go 自身的输出也是异步的. 没有 direct io

**Comment by spiderpoison** [comment]
go自身的输出，如，os.Write应该是调用syscall发数据发给系统后返回，并有for{}等待放成功，这样的话应该不是异步吧？
https://github.com/golang/go/blob/1b9374450bbf3372f18915deb58ed11a072eef4a/src/internal/poll/fd_unix.go#L254-L287
我是想给zap做配套的文件落磁盘，如，我在程序里调用zap的接口打印日志，zap最后会同步调用WriteSyncer的write，这里如果我直接放上os.Write，我担心磁盘IO会影响正常的逻辑。

**Comment by arthurkiller** [comment]
不会, 因为你的 syscall 之后是走 pagecahe , 其实并没有 直接落盘,  go 本身实现了用户态的 aio. 因此我们不需要担心这个,

我这里的 异步, 其实没有想特别明白能否起到优化, 我们自己使用中也没有用到其实, 我们都是 lock 的方式., 

这个异步的话, 主要是想做一个平滑和削峰, 当一个大的事件触发大量的日志时, 能够从writer 这边避免大量的 io 同时堆积到 系统这边. 但是也没有特别的验证过.

我个人建议(也是大量的线上实践经验),. zap 使用 lock 方式就足够了.

或者我说的有哪些不太对的请指出:)

**Comment by spiderpoison** [comment]
非常感谢您的耐心回答，我也先用zap的lock方式，和同步rollingwrite。
也从下面这篇文章，了解了golang磁盘io的情况
http://xiaorui.cc/2018/04/23/disk-io%e5%bc%95%e8%b5%b7golang%e7%ba%bf%e7%a8%8b%e6%95%b0%e6%9a%b4%e6%b6%a8%e7%9a%84%e9%97%ae%e9%a2%98/

这个issue我先关了

**Comment by arthurkiller** [comment]
np, 有问题可以随时沟通

**Comment by arthurkiller** [comment]
async 我修复后就 push dev 了
