### ISSUE TITLE
应用重启后最大保存的文件数就不正确

### ISSUE THREAD

**Issue by mq0427** [arthurkiller/rollingwriter#21]
应用重启后最大保存的文件数就不正确了，好像又重新开始算了。这样随着应用的不断重启，可能保存的文件数越来越多。

**Comment by arthurkiller** [comment]
emm 是的，目前是有这个问题，我还没修复。有兴趣的话可以贡献一个 pr

逻辑应该就是启动时，根据日志文件的名称格式，遍历日志文件夹下的所有日志，解析日志时间后，重置计数

**Comment by arthurkiller** [comment]
closed via #22
