### ISSUE TITLE
Buffer writer concurrency unsafe

### ISSUE THREAD

**Issue by koveango** [arthurkiller/rollingwriter#25]
https://github.com/arthurkiller/rollingwriter/blob/master/writer.go#L365
```go
func (w *BufferWriter) Write(b []byte) (int, error) {
	// ...
	buf := append(*w.buf, b...)
	atomic.StorePointer((*unsafe.Pointer)(unsafe.Pointer(&w.buf)), (unsafe.Pointer)(&buf))
```

Hi，我使用到了贵包rollingwriter的buffer writer，测试时候发现会有丢日志的情况(高并发场景)。初步分析发现应该是这里的buffer append 非并发安全导致的。

比如buffer里已有 line1，并发两个Write，分别写入 line2、line3，竞争激烈的情况下，StorePointer可能会出现 [line1, line3] 覆盖 [line1, line2]，从而导致line2丢失。

测试时加上了给这行代码加了个mutex or trylock，发现可以解决丢日志的问题。这个问题也希望跟 @arthurkiller 作者大大确认下有无理解上的偏差。

`From`
```go
buf := append(*w.buf, b...)
atomic.StorePointer((*unsafe.Pointer)(unsafe.Pointer(&w.buf)), (unsafe.Pointer)(&buf))
```
`To`
```go
w.lockBuf.Lock()
*(w.buf) = append(*w.buf, b...)
w.lockBuf.Unlock()
```

另，spinlock简单实现
```go

type Locker struct {
	lock uintptr
}

func (l *Locker) Lock() {
	for !atomic.CompareAndSwapUintptr(&l.lock, 0, 1) {
		runtime.Gosched()
	}
}

func (l *Locker) Unlock() {
	atomic.StoreUintptr(&l.lock, 0)
}
```

**Comment by arthurkiller** [comment]
@koveango 收到，我调查一下，也欢迎提交 MR

**Comment by koveango** [comment]
Hi @arthurkiller ，我提交了一个MR来修复这个问题，有时间辛苦review下逻辑~

**Comment by arthurkiller** [comment]
good catch, thx for your contribution! @koveango
