### ISSUE TITLE
Schedule for v2.0

### ISSUE THREAD

**Issue by ipfans** [arthurkiller/rollingwriter#26]
Any updates for v2.0?

**Comment by arthurkiller** [comment]
@ipfans if you have some feature in need, please let me know~

**Comment by ipfans** [comment]
@arthurkiller Nothing for now. But I saw README mention v2.0 is coming.

**Comment by arthurkiller** [comment]
> @arthurkiller Nothing for now. But I saw README mention v2.0 is coming.

it is LOL
