### ISSUE TITLE
FileName use template string

### ISSUE THREAD

**Issue by frank-yf** [arthurkiller/rollingwriter#35]
For **FileName**, consider using template strings, such as `foo-${date}.log.gz`, which makes the file suffix reasonable. 
It's strange to force a **TimeTag** spliced to the end of **FileName**.
Last, thanks for your components, which helped me a lot~

**Comment by yuefei7746** [comment]
or **Printf**

**Comment by arthurkiller** [comment]
Hi, @yuefei7746
Glad to see it really helps, and PR is welcomed. You can add features by contributing to this repo.
