### ISSUE TITLE
如何同 zap 搭配使用啊？demo 中能否加上示例

### ISSUE THREAD

**Issue by xunxinyuan** [arthurkiller/rollingWriter#4]
刚开始看 zap 的源码，还未找到如何使用 rollingWriter 同 zap 搭配。
若有示例就更棒了，感谢感谢。

**Comment by arthurkiller** [comment]
这个库只是一个iowriter，并不跟zap有任何耦合，所以不会提供关于zap的任何demo

可以去看下zap的文档
Have an awesome day

✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by xunxinyuan** [comment]
ok,了解了。感谢。
看 zap 源码也知道怎么搭配使用了。
