### ISSUE TITLE
goroutne leak

### ISSUE THREAD

**Issue by runner-mei** [arthurkiller/rollingwriter#42]
![图片](https://user-images.githubusercontent.com/1052632/174264491-52b83498-749f-44d4-8d0a-92a48a08ee12.png)

当  RollingPolicy 为 VolumeRolling 时你启动了一个 goroutine，  然后我没有人关闭它， 调 writer 的 Close() 时不能关闭这个 goroutine

而且这个 goroutine 中的  timer 就算是 goroutine 退出了，也没有有停止这个 Ticker

**Comment by runner-mei** [comment]
这个有一个  https://github.com/arthurkiller/rollingwriter/pull/43

**Comment by runner-mei** [comment]
另外 cron 也不是完全线程安全的， 你调用 stop 时有一个概率失败

**Comment by arthurkiller** [comment]
嗯，volume 这里确实有 leak

后面整体加一下测试case 的覆盖率

**Comment by arthurkiller** [comment]
感谢 bug fix
