### ISSUE TITLE
Why we need _asyncBufferPool for async writer?

### ISSUE THREAD

**Issue by mm2175** [arthurkiller/rollingwriter#46]
We already have []byte allocated, since the signature of Write([]byte) method, why use _asyncBufferPool? It add additional copy which seems unnecessary?

**Comment by arthurkiller** [comment]
> We already have []byte allocated, since the signature of Write([]byte) method, why use _asyncBufferPool? It add additional copy which seems unnecessary?

`Logger` need to take ownership of the log entry, that's why we need at least one copy. `_asyncBuffer` can save the object allocation cost.

**Comment by mm2175** [comment]
Sorry for that I don't quite understand why Logger need take ownership of the log entry? []byte is passwed through method paramter.

**Comment by chikaku** [comment]
Some upper-level log library like `zap` may use `rollingwriter` as `Writer`. And the `[]byte` data is passed by them, but they may **reuse it after `Write` returns**.

So if using `AsynchronousWriter` or `BufferWriter` and didn't copy it, there will be a data race before the data is actually written to the file.

https://github.com/uber-go/zap/blob/a55bdc32f526699c3b4cc51a2cc97e944d02fbbf/zapcore/core.go#L94

```go
func (c *ioCore) Write(ent Entry, fields []Field) error {
	buf, err := c.enc.EncodeEntry(ent, fields)
	if err != nil {
		return err
	}
	_, err = c.out.Write(buf.Bytes()) // pass it into a Asynchronous Writer
	buf.Free()                        // this buf may be overwritten elsewhere
        // ...
}
```

**Comment by mm2175** [comment]
Thanks for your reply @arthurkiller and your detailed explanation @chikaku , now I understand.
