### ISSUE TITLE
async模式的buffer大小，存在严重的性能问题

### ISSUE THREAD

**Issue by AprilFiv** [arthurkiller/rollingwriter#47]
async模式中，在上层日志组件调用Write时，会通过golang的sync.pool中获取一个1M的[]byte。

golang gc pacer在某些情况下可能出现运行速率的预估错误（推测和这个buffer的大小和缓存命中率有关），导致较晚开始gc。此时除了25%的并发标记P，其余P调度的goroutine如果需要写日志时，若需要分配[]byte对象，由于[]byte过大，达到了1M，分配速率非常快，不得不进入Mark Assist，或者迅速进入下一次GC，导致大量的调度延迟，进而使程序的毛刺非常严重。

**在尝试缩小这个[]byte对象的大小之后，程序的毛刺现象有非常明显的缓解**。

我有两个提议：
1. 缩小[]byte的分配大小，如1KB或者10KB。程序的日志一般而言超过100KB的都比较少，分配1M实属没有必要。 
-----程序需要一定时间自适应调整[]byte的大小，一开始[]byte对象的复用性可能较差，如果日志普遍较大的话。
2. 不使用Sync.Pool，既然在写入时异步刷入有QueueSize(1024)的写入速率限制，不妨设置一个1024大小的Queue，用来维护一个常驻内存的BufferPool。
------维持[]byte 1M且1024大小的话，常驻内存会达到1个G，同时可能对GC scanObject带来一点的额外压力，如果要增大size的话。
------可以缩小[]byte，同1，可以分配在堆外内存，减少gc scanObject的开销。

**Comment by arthurkiller** [comment]
感觉 1 比较合理，确实很少有特别大的log

**Comment by AprilFiv** [comment]
原issue关于syncPool的描述存在谬误，已编辑。

这个值是否可以在接下来的版本中设置成1KB？或者添加参数支持初始化？

**Comment by arthurkiller** [comment]
> 原issue关于syncPool的描述存在谬误，已编辑。
> 
> 这个值是否可以在接下来的版本中设置成1KB？或者添加参数支持初始化？

@AprilFiv 感谢关注这个项目，我觉得可以设置默认1kb并加一个config option，如果方便的话可以直接提一个 PR

**Comment by arthurkiller** [comment]
比较大的对象确实容易导致 gc 的抖动，之前默认值不是特别合理

**Comment by AprilFiv** [comment]
#48

**Comment by arthurkiller** [comment]
@AprilFiv btw 

问一下，你们是什么场景下使用的 async writer 呢，或者对于这个的场景有没有一个描述?

其实对于这个 writer 的合理性来说，我一直是存疑的，这个主要是想 buffer 住一些用户态的写入削减 io ops，原本是期望作进一步的merge，但是感觉从go 的模型看讲不通，一方面质疑这个设计的目的其实是伪命题，一方面质疑这个场景其实不存在

或者，你们有针对其他的writer 类型进行测试么？

**Comment by AprilFiv** [comment]
> @AprilFiv btw
> 
> 问一下，你们是什么场景下使用的 async writer 呢，或者对于这个的场景有没有一个描述?
> 
> 其实对于这个 writer 的合理性来说，我一直是存疑的，这个主要是想 buffer 住一些用户态的写入削减 io ops，原本是期望作进一步的merge，但是感觉从go 的模型看讲不通，一方面质疑这个设计的目的其实是伪命题，一方面质疑这个场景其实不存在
> 
> 或者，你们有针对其他的writer 类型进行测试么？

实话说我也存疑，不对写入做merge，使用async模式并不能在性能上有所提升。
使用'none'模式的writer在吞吐表现上相比于'async'表现优异得多。
我们对rollingwriter的依赖是因为引用了其他框架对这个组件的依赖，而模式是’async‘。具体的设计哲学和框架开发者的思考我并不理解。

**Comment by arthurkiller** [comment]
> > @AprilFiv btw
> > 问一下，你们是什么场景下使用的 async writer 呢，或者对于这个的场景有没有一个描述?
> > 其实对于这个 writer 的合理性来说，我一直是存疑的，这个主要是想 buffer 住一些用户态的写入削减 io ops，原本是期望作进一步的merge，但是感觉从go 的模型看讲不通，一方面质疑这个设计的目的其实是伪命题，一方面质疑这个场景其实不存在
> > 或者，你们有针对其他的writer 类型进行测试么？
> 
> 实话说我也存疑，不对写入做merge，使用async模式并不能在性能上有所提升。 使用'none'模式的writer在吞吐表现上相比于'async'表现优异得多。 我们对rollingwriter的依赖是因为引用了其他框架对这个组件的依赖，而模式是’async‘。具体的设计哲学和框架开发者的思考我并不理解。

感谢回复，如果有可能，可以建议依赖的框架改成使用 none 模式
async 后面的版本应该会移除

**Comment by mm2175** [comment]
> @AprilFiv btw
> 
> 问一下，你们是什么场景下使用的 async writer 呢，或者对于这个的场景有没有一个描述?
> 
> 其实对于这个 writer 的合理性来说，我一直是存疑的，这个主要是想 buffer 住一些用户态的写入削减 io ops，原本是期望作进一步的merge，但是感觉从go 的模型看讲不通，一方面质疑这个设计的目的其实是伪命题，一方面质疑这个场景其实不存在
> 
> 或者，你们有针对其他的writer 类型进行测试么？

我们的使用场景是经常登录服务器 grep 日志查看（规模不大，没有必要弄集中日志收集那种），同步模式 grep 日志会导致正在运行的程序受影响，换了 async 之后好很多。

**Comment by phuslu** [comment]
> 实话说我也存疑，不对写入做merge，使用async模式并不能在性能上有所提升。

我在 phuslu/log 引入了 writev 实现批量写入而避免了额外的应用层buffer，可以看 https://github.com/phuslu/log?tab=readme-ov-file#async-file-writer

在github actions的测试可以看到[写入吞吐提高了10倍](https://github.com/phuslu/log/actions/runs/10123465715/job/27996773231)，如图

![image](https://github.com/user-attachments/assets/64c7b48f-2914-4318-98f8-a88944db9c2d)


PS: 据我目前所知这应该是目前go语言日志库的唯一的writev实现的异步writer，所以就来冒昧推荐了。
