### ISSUE TITLE
write error: can't rename log file: rename / /-2023-04-26T11-45-46.770: device or resource busy

### ISSUE THREAD

**Issue by oyb001** [arthurkiller/rollingwriter#49]
@arthurkiller  Hello
zap.logger write error
```shell
2023-04-26 19:45:46.770523613 +0800 CST m=+6.113431489 write error: can't rename log file: rename / /-2023-04-26T11-45-46.770: device or resource busy
{"level":"INFO","ts":"2023-04-26T19:45:46.770+0800","caller":"core/task_manager.go:78","msg":"TaskManager:EsSearch:start","ServerName":"monitor-log-metric-calc"}
2023-04-26 19:45:46.770685539 +0800 CST m=+6.113593399 write error: can't rename log file: rename / /-2023-04-26T11-45-46.770: device or resource busy
```
Environment:
```text
Os:ubantu 5.4.0-72-generic #80~18.04.1-Ubuntu SMP Mon Apr 12 23:26:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
go version:go1.19
```
Log Config:
```go

var logger *zap.Logger

func Setup(config *config.Config) *zap.Logger {

	var filepath = fmt.Sprintf("%s/%s",
		config.Log.LogSavePath,
		config.Log.LogFileName)
	var coreArr []zapcore.Core

	//获取编码器
	//encoderConfig := zap.NewProductionConfig()
	encoderConfig := zap.NewProductionEncoderConfig()     //NewJSONEncoder()输出json格式，NewConsoleEncoder()输出普通文本格式
	encoderConfig.EncodeTime = zapcore.ISO8601TimeEncoder //指定时间格式
	//encoderConfig.EncodeLevel = zapcore.CapitalColorLevelEncoder    //按级别显示不同颜色，不需要的话取值zapcore.CapitalLevelEncoder就可以了
	encoderConfig.EncodeLevel = zapcore.CapitalLevelEncoder //按级别显示不同颜色，不需要的话取值zapcore.CapitalLevelEncoder就可以了
	//encoderConfig.EncodeCaller = zapcore.FullCallerEncoder        //显示完整文件路径
	//encoder := zapcore.NewConsoleEncoder(encoderConfig)
	encoder := zapcore.NewJSONEncoder(encoderConfig)

	//日志级别
	highPriority := zap.LevelEnablerFunc(func(lev zapcore.Level) bool { //error级别
		return lev >= zap.ErrorLevel
	})
	lowPriority := zap.LevelEnablerFunc(func(lev zapcore.Level) bool { //info和debug级别,debug级别是最低的
		return lev < zap.ErrorLevel && lev >= zap.DebugLevel
	})

	//info文件writeSyncer
	infoFileWriteSyncer := zapcore.AddSync(&lumberjack.Logger{
		Filename:   filepath,                 //日志文件存放目录，如果文件夹不存在会自动创建
		MaxSize:    config.Log.LogMaxSize,    //文件大小限制,单位MB
		MaxBackups: config.Log.LogMaxBackups, //最大保留日志文件数量
		MaxAge:     config.Log.LogMaxAge,     //日志文件保留天数
		Compress:   false,                    //是否压缩处理
	})
	infoFileCore := zapcore.NewCore(encoder, zapcore.NewMultiWriteSyncer(infoFileWriteSyncer, zapcore.AddSync(os.Stdout)), lowPriority) //第三个及之后的参数为写入文件的日志级别,ErrorLevel模式只记录error级别的日志
	//error文件writeSyncer
	errorFileWriteSyncer := zapcore.AddSync(&lumberjack.Logger{
		Filename:   filepath,                 //日志文件存放目录
		MaxSize:    config.Log.LogMaxSize,    //文件大小限制,单位MB
		MaxBackups: config.Log.LogMaxBackups, //最大保留日志文件数量
		MaxAge:     config.Log.LogMaxAge,     //日志文件保留天数
		Compress:   false,                    //是否压缩处理
	})
	errorFileCore := zapcore.NewCore(encoder, zapcore.NewMultiWriteSyncer(errorFileWriteSyncer, zapcore.AddSync(os.Stdout)), highPriority) //第三个及之后的参数为写入文件的日志级别,ErrorLevel模式只记录error级别的日志

	coreArr = append(coreArr, infoFileCore)
	coreArr = append(coreArr, errorFileCore)
	logger = zap.New(zapcore.NewTee(coreArr...), zap.AddCaller(), zap.Fields(
		zap.String("ServerName", ServerName))) //zap.AddCaller()为显示文件名和行号，可省略,增加预定义服务字段

	//logger.Info("hello info")
	//logger.Debug("hello debug")
	//logger.Error("hello error")
	return logger
}

// Debug : Level 0
func GetSuger() *zap.SugaredLogger {
	return logger.Sugar()
}

```

**Comment by arthurkiller** [comment]
io device busy, can you reproduce this issue?Have an awesome day✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️Arthur leeSent from my iPhone在 2023年4月26日，下午7:55，ouyangbin ***@***.***> 写道：﻿
@arthurkiller  Hello
zap.logger write error
2023-04-26 19:45:46.770523613 +0800 CST m=+6.113431489 write error: can't rename log file: rename / /-2023-04-26T11-45-46.770: device or resource busy
{"level":"INFO","ts":"2023-04-26T19:45:46.770+0800","caller":"core/task_manager.go:78","msg":"TaskManager:EsSearch:start","ServerName":"monitor-log-metric-calc"}
2023-04-26 19:45:46.770685539 +0800 CST m=+6.113593399 write error: can't rename log file: rename / /-2023-04-26T11-45-46.770: device or resource busy
Environment:
Os:ubantu 5.4.0-72-generic #80~18.04.1-Ubuntu SMP Mon Apr 12 23:26:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
go version:go1.19

Log Config:
var logger *zap.Logger

func Setup(config *config.Config) *zap.Logger {

	var filepath = fmt.Sprintf("%s/%s",
		config.Log.LogSavePath,
		config.Log.LogFileName)
	var coreArr []zapcore.Core

	//获取编码器
	//encoderConfig := zap.NewProductionConfig()
	encoderConfig := zap.NewProductionEncoderConfig()     //NewJSONEncoder()输出json格式，NewConsoleEncoder()输出普通文本格式
	encoderConfig.EncodeTime = zapcore.ISO8601TimeEncoder //指定时间格式
	//encoderConfig.EncodeLevel = zapcore.CapitalColorLevelEncoder    //按级别显示不同颜色，不需要的话取值zapcore.CapitalLevelEncoder就可以了
	encoderConfig.EncodeLevel = zapcore.CapitalLevelEncoder //按级别显示不同颜色，不需要的话取值zapcore.CapitalLevelEncoder就可以了
	//encoderConfig.EncodeCaller = zapcore.FullCallerEncoder        //显示完整文件路径
	//encoder := zapcore.NewConsoleEncoder(encoderConfig)
	encoder := zapcore.NewJSONEncoder(encoderConfig)

	//日志级别
	highPriority := zap.LevelEnablerFunc(func(lev zapcore.Level) bool { //error级别
		return lev >= zap.ErrorLevel
	})
	lowPriority := zap.LevelEnablerFunc(func(lev zapcore.Level) bool { //info和debug级别,debug级别是最低的
		return lev < zap.ErrorLevel && lev >= zap.DebugLevel
	})

	//info文件writeSyncer
	infoFileWriteSyncer := zapcore.AddSync(&lumberjack.Logger{
		Filename:   filepath,                 //日志文件存放目录，如果文件夹不存在会自动创建
		MaxSize:    config.Log.LogMaxSize,    //文件大小限制,单位MB
		MaxBackups: config.Log.LogMaxBackups, //最大保留日志文件数量
		MaxAge:     config.Log.LogMaxAge,     //日志文件保留天数
		Compress:   false,                    //是否压缩处理
	})
	infoFileCore := zapcore.NewCore(encoder, zapcore.NewMultiWriteSyncer(infoFileWriteSyncer, zapcore.AddSync(os.Stdout)), lowPriority) //第三个及之后的参数为写入文件的日志级别,ErrorLevel模式只记录error级别的日志
	//error文件writeSyncer
	errorFileWriteSyncer := zapcore.AddSync(&lumberjack.Logger{
		Filename:   filepath,                 //日志文件存放目录
		MaxSize:    config.Log.LogMaxSize,    //文件大小限制,单位MB
		MaxBackups: config.Log.LogMaxBackups, //最大保留日志文件数量
		MaxAge:     config.Log.LogMaxAge,     //日志文件保留天数
		Compress:   false,                    //是否压缩处理
	})
	errorFileCore := zapcore.NewCore(encoder, zapcore.NewMultiWriteSyncer(errorFileWriteSyncer, zapcore.AddSync(os.Stdout)), highPriority) //第三个及之后的参数为写入文件的日志级别,ErrorLevel模式只记录error级别的日志

	coreArr = append(coreArr, infoFileCore)
	coreArr = append(coreArr, errorFileCore)
	logger = zap.New(zapcore.NewTee(coreArr...), zap.AddCaller(), zap.Fields(
		zap.String("ServerName", ServerName))) //zap.AddCaller()为显示文件名和行号，可省略,增加预定义服务字段

	//logger.Info("hello info")
	//logger.Debug("hello debug")
	//logger.Error("hello error")
	return logger
}

// Debug : Level 0
func GetSuger() *zap.SugaredLogger {
	return logger.Sugar()
}

**Comment by oyb001** [comment]
@arthurkiller  Can reproduce in my test server
```shell
{"level":"INFO","ts":"2023-04-27T17:15:46.408+0800","caller":"core/task_manager.go:221","msg":"MongoSearch:start","ServerName":"monitor-log-metric-calc"}
2023-04-27 17:15:46.408200873 +0800 CST m=+2.943403693 write error: can't rename log file: rename / /-2023-04-27T09-15-46.408: device or resource busy
{"level":"ERROR","ts":"2023-04-27T17:15:46.408+0800","caller":"core/task_manager.go:215","msg":"mongod查询异常：","ServerName":"monitor-log-metric-calc","ErrInf":"runtime error: invalid memory address or nil pointer dereference"}
2023-04-27 17:15:46.408226307 +0800 CST m=+2.943429127 write error: can't rename log file: rename / /-2023-04-27T09-15-46.408: device or resource busy
{"level":"INFO","ts":"2023-04-27T17:15:46.408+0800","caller":"core/task_manager.go:78","msg":"TaskManager:EsSearch:start","ServerName":"monitor-log-metric-calc"}
2023-04-27 17:15:46.408249017 +0800 CST m=+2.943451837 write error: can't rename log file: rename / /-2023-04-27T09-15-46.408: device or resource busy
{"level":"INFO","ts":"2023-04-27T17:15:46.408+0800","caller":"core/task_manager.go:114","msg":"Es:Search:start","ServerName":"monitor-log-metric-calc","TaskNum":0}
2023-04-27 17:15:46.408268507 +0800 CST m=+2.943471348 write error: can't rename log file: rename / /-2023-04-27T09-15-46.408: device or resource busy
{"level":"INFO","ts":"2023-04-27T17:15:46.408+0800","caller":"core/task_manager.go:145","msg":"Es:Search:end","ServerName":"monitor-log-metric-calc","TaskNum":0}
2023-04-27 17:15:46.408290781 +0800 CST m=+2.943493601 write error: can't rename log file: rename / /-2023-04-27T09-15-46.408: device or resource busy
{"level":"INFO","ts":"2023-04-27T17:15:46.408+0800","caller":"core/task_manager.go:82","msg":"TaskManager:EsSearch:End","ServerName":"monitor-log-metric-calc"}
```
Os kernel conf
```shell
[root@test- ~]# sysctl -a | grep file
fs.file-max = 65535
fs.file-nr = 2048       0       65535
fs.xfs.filestream_centisecs = 3000
```

**Comment by oyb001** [comment]
That time iostatus
```shell
[root@test]# iostat 
Linux 3.10.0-1127.el7.x86_64 (test)         04/27/2023      _x86_64_        (2 CPU)

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           4.31    0.00    0.32    0.03    0.00   95.34

Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sda               3.57         0.01        91.92     437760 5551424302
dm-0              3.45         0.00        91.08     295875 5500923282
dm-1              0.13         0.00         0.84     112238   50498822

```

**Comment by oyb001** [comment]
@arthurkiller, close issue.
It was my program that had an endless loop,So it caused a lot log writes.
