### ISSUE TITLE
按大小翻滚的检测任务在获取FD后未释放，导致FD泄露

### ISSUE THREAD

**Issue by GitMoons** [arthurkiller/rollingWriter#5]

**Comment by arthurkiller** [comment]
correct, this has been fixed on another repo. and I forget to update to this repo.😂

**Comment by arthurkiller** [comment]
I will fix this soon. And this repo need a reconstruct either.

**Comment by museghost** [comment]
hello arthurkiller.

I am a fan of the zap and your rollingwriter and .. it's awesome ! :)

Could you please update current master or dev repo for using the fix of the FD async issue ?

Best regards

**Comment by arthurkiller** [comment]
np, Will fix it tonight

Have an awesome day

✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by arthurkiller** [comment]
I just on vacation these days... 

Have an awesome day

✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by museghost** [comment]
@arthurkiller I see :) The vacation is a source of our happy life !

**Comment by arthurkiller** [comment]
Wait a minute. seems I had already fixed on d77e5d907c73b73bdb17cad30a04d9e034284b1f
Have you tried the latest master?

Have an awesome day

✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee

**Comment by arthurkiller** [comment]
Ohhhh I was confused. They are different bugs.

Have an awesome day

✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️
Arthur lee
