### ISSUE TITLE
onRotate callback function, file extension option. 

### ISSUE THREAD

**Issue by mosajjal** [arthurkiller/rollingwriter#52]
Hi, 

Love this project and been using it for a while. Now I'm interested in using it for `parquet` files and use this to auto rotate them. two things would be ideal:

1) ability to change the default `.log` extension (https://github.com/arthurkiller/rollingwriter/blob/965c6fc2d193824917a3d8b701880a6cc8422d30/rollingwriter.go#L145)

2) it would be really nice to have a callback function when file rotation happens. this way, I can re-create the `parquet` schema each time the file rolls over and the file consistency will remain the same. I guess the same could be said for rotating CSV files and other types that have some sort of header as well. 

if this is something you're keen to add, happy to draft a PR for it.

**Comment by arthurkiller** [comment]
> Hi,
> 
> Love this project and been using it for a while. Now I'm interested in using it for `parquet` files and use this to auto rotate them. two things would be ideal:
> 
> 1. ability to change the default `.log` extension (https://github.com/arthurkiller/rollingwriter/blob/965c6fc2d193824917a3d8b701880a6cc8422d30/rollingwriter.go#L145
>    )
> 2. it would be really nice to have a callback function when file rotation happens. this way, I can re-create the `parquet` schema each time the file rolls over and the file consistency will remain the same. I guess the same could be said for rotating CSV files and other types that have some sort of header as well.
> 
> if this is something you're keen to add, happy to draft a PR for it.

hi, thx for your love. You can just put a PR, that's cool

**Comment by arthurkiller** [comment]
merged, thanks again

**Comment by mosajjal** [comment]
cool :) appreciate your quick turnaround for this. I'll raise another PR for the callback func.
